version: '3'

services:
  maddm:
    build: .
    image: valentem1992/maddm
    volumes:
      - '$PWD/DMsimp_s_spin0_MD:/home/hep/MG5_aMC_v2_6_3_2/models/DMsimp_s_spin0_MD'
      - '$PWD/scripts:/home/hep/MG5_aMC_v2_6_3_2/scripts'
      - '$PWD/output:/home/hep/MG5_aMC_v2_6_3_2/output'
    command: ./bin/maddm.py -f scripts/maddm-test.py